# Generated by Django 5.1 on 2024-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='registroveterinario',
            field=models.FileField(blank=True, null=True, upload_to='veterinario/'),
        ),
    ]
